// Generated by CoffeeScript 1.5.0
(function() {
  var expect, ph, phantom, server, serverPath, testHelpers;

  process.env.NODE_ENV = "testing";

  expect = require("chai").expect;

  testHelpers = require("./testHelpers");

  phantom = require("phantom");

  server = {};

  ph = {};

  serverPath = "";

  before(function(done) {
    this.timeout(10000);
    return testHelpers.startServer(function(err, result) {
      if (err) {
        return done(err);
      }
      serverPath = result;
      return phantom.create(function(phantomInstance) {
        ph = phantomInstance;
        return done();
      });
    });
  });

  describe("Headless Browser test example: Open homepage", function() {
    var page;
    page = {};
    before(function(done) {
      return ph.createPage(function(p) {
        return p.open(serverPath, function(status) {
          page = p;
          return done();
        });
      });
    });
    it("should be able to open page successfully with correct page title", function(done) {
      return page.evaluate((function() {
        return document.title;
      }), function(result) {
        expect(result).to.be.equal("Hello there!");
        return done();
      });
    });
    it("should contain 3 input boxes", function(done) {
      return page.evaluate(function() {
        var inputs;
        inputs = document.querySelectorAll("input[type=text]");
        return inputs.length;
      }, function(result) {
        expect(result).to.be.equal(3);
        return done();
      });
    });
    return it("should contain a submit button", function(done) {
      return page.evaluate(function() {
        var submit;
        submit = document.querySelectorAll("input[type=submit]");
        return submit.length;
      }, function(result) {
        expect(result).to.be.equal(1);
        return done();
      });
    });
  });

  describe("Headless browser test example: Submitting a form", function() {
    var page;
    page = {};
    before(function(done) {
      this.timeout(10000);
      return ph.createPage(function(p) {
        page = p;
        return page.open(serverPath, function(status) {
          page.set("onLoadFinished", function(status) {
            return done();
          });
          return page.evaluate(function() {
            var ageInput, foodInput, nameInput;
            nameInput = document.getElementById("input-name");
            nameInput.value = "Caesar";
            ageInput = document.getElementById("input-age");
            ageInput.value = 15;
            foodInput = document.getElementById("input-food");
            foodInput.value = "salad";
            return document.form.submit();
          }, function() {});
        });
      });
    });
    it("should say Hello Caesar at the next page", function(done) {
      return page.evaluate(function() {
        var title;
        title = document.querySelector("h1");
        return title.innerText;
      }, function(result) {
        expect(result).to.be.equal("Hello Caesar!");
        return done();
      });
    });
    return it("should show Caesar's name and age and favorite food", function(done) {
      return page.evaluate(function() {
        var result;
        result = document.querySelector(".result");
        return result.innerText;
      }, function(result) {
        expect(result).to.be.equal("Now I know that your name is Caesar, your age is 15 and your favorite food is salad.");
        return done();
      });
    });
  });

  after(function(done) {
    return testHelpers.clearDatabase(function() {
      ph.exit();
      return testHelpers.stopServer(serverPath, function() {
        return done();
      });
    });
  });

}).call(this);
