// Generated by CoffeeScript 1.5.0
(function() {
  var expect, helpers;

  process.env.NODE_ENV = "testing";

  expect = require("chai").expect;

  helpers = require("../lib/helpers");

  describe("Module testing example: Input validation", function() {
    var validateAge;
    validateAge = helpers.validateAge;
    it("should return true if valid age is given", function() {
      var val;
      val = validateAge(10);
      return expect(val).to.be["true"];
    });
    it("should return false if given a pure string", function() {
      var val;
      val = validateAge("donkey");
      return expect(val).to.be["false"];
    });
    it("should return false if given a number + string combination", function() {
      var val;
      val = validateAge("10 years old");
      return expect(val).to.be["false"];
    });
    return it("should run 10000 iterations successfully", function() {
      var i, val, _i, _results;
      _results = [];
      for (i = _i = 0; _i < 10000; i = ++_i) {
        val = validateAge(10);
        _results.push(expect(val).to.be["true"]);
      }
      return _results;
    });
  });

}).call(this);
