// Generated by CoffeeScript 1.5.0
(function() {
  var app, express, http;

  express = require("express");

  http = require("http");

  app = express();

  app.configure(function() {
    app.set("port", process.env.PORT || 3000);
    app.set("views", __dirname + "/views");
    app.set("view engine", "jade");
    app.use(express.favicon());
    app.use(express.bodyParser());
    app.use(express.methodOverride());
    app.use(app.router);
    return app.use(express["static"](__dirname + "/public"));
  });

  app.configure("development", function() {
    app.use(express.logger("dev"));
    return app.use(express.errorHandler());
  });

  app.get("/", require("./routes/home"));

  app.post("/submit", require("./routes/submit"));

  http.createServer(app).listen(app.get("port"), function() {
    return console.log("Express server listening on http://localhost:" + app.get("port"));
  });

}).call(this);
