// Generated by CoffeeScript 1.5.0
(function() {

  module.exports = function(req, res) {
    res.locals.error = "";
    res.locals.title = "Hello there!";
    return res.render("index");
  };

}).call(this);
