// Generated by CoffeeScript 1.5.0
(function() {
  var conf, confs, env;

  confs = {
    "development": {
      "db": "mongodb://localhost/myapp-dev"
    },
    "testing": {
      "db": "mongodb://localhost/myapp-test"
    }
  };

  env = process.env.NODE_ENV;

  if (!env) {
    process.env.NODE_ENV = "development";
  }

  conf = confs[env];

  if (!conf) {
    conf = confs["development"];
  }

  module.exports = conf;

}).call(this);
