// Generated by CoffeeScript 1.5.0
(function() {
  var conf, confs, env;

  confs = {
    "development": {
      "db": "mongodb://localhost/myapp-dev"
    },
    "testing": {
      "db": "mongodb://localhost/myapp-test"
    },
    "staging": {
      "db": "mongodb://localhost/myapp-stag"
    },
    "production": {
      "db": "mongodb://localhost/myapp-prod"
    }
  };

  env = process.env.NODE_ENV || "development";

  conf = confs[env] || confs["development"];

  module.exports = conf;

}).call(this);
