// Generated by CoffeeScript 1.5.0
(function() {
  var validateAge;

  validateAge = function(input) {
    return !isNaN(parseFloat(input)) && isFinite(input);
  };

  module.exports = {
    validateAge: validateAge
  };

}).call(this);
