// Generated by CoffeeScript 1.5.0
(function() {
  var Schema, User, conf, mongoose, userSchema;

  mongoose = require("mongoose");

  Schema = mongoose.Schema;

  conf = require("./conf");

  mongoose.connect(conf.db);

  userSchema = new Schema({
    name: String,
    age: Number,
    food: String
  });

  User = mongoose.model('User', userSchema);

  module.exports = {
    User: User
  };

}).call(this);
