// Generated by CoffeeScript 1.5.0
(function() {
  var User, createOrUpdateUser, getUser, validateAge;

  User = require("./models").User;

  validateAge = require("./helpers").validateAge;

  getUser = function(data, callback) {
    var query;
    if (!data.name) {
      return callback("Name is required");
    }
    query = User.findOne({});
    query.where("name", data.name);
    if (data.age) {
      query.where("age", data.age);
    }
    return query.exec(callback);
  };

  createOrUpdateUser = function(data, callback) {
    if (!data.name) {
      return callback("Name is required");
    }
    if (!data.age) {
      return callback("Age is required");
    }
    if (!validateAge(data.age)) {
      return callback("Age must be a number");
    }
    return User.update({
      name: data.name,
      age: data.age
    }, {
      name: data.name,
      age: data.age,
      food: data.food
    }, {
      upsert: true
    }, callback);
  };

  module.exports = {
    getUser: getUser,
    createOrUpdateUser: createOrUpdateUser
  };

}).call(this);
